/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipmentsRouteImport } from './routes/equipments'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as OurClientsRouteImport } from './routes/our-clients'
import { Route as OurInfrastructureRouteImport } from './routes/our-infrastructure'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RepairProcessRouteImport } from './routes/repair-process'
import { Route as RequestRepairRouteImport } from './routes/request-repair'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TrackRepairRouteImport } from './routes/track-repair'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as WarrantyAndServiceRouteImport } from './routes/warranty-and-service'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as EquipmentsSlugRouteImport } from './routes/equipments.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin/enquiries'
import { Route as AuthenticatedAdminImagesRouteImport } from './routes/_authenticated/admin/images'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminRepairRequestsRouteImport } from './routes/_authenticated/admin/repair-requests'
import { Route as AuthenticatedAdminRepairsRouteImport } from './routes/_authenticated/admin/repairs'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin/requests'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated/admin/tracking'
import { Route as AuthenticatedAdminOrdersOrderIdRouteImport } from './routes/_authenticated/admin/orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentsRoute = EquipmentsRouteImport.update({
  id: '/equipments',
  path: '/equipments',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const OurClientsRoute = OurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const OurInfrastructureRoute = OurInfrastructureRouteImport.update({
  id: '/our-infrastructure',
  path: '/our-infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairProcessRoute = RepairProcessRouteImport.update({
  id: '/repair-process',
  path: '/repair-process',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRepairRoute = RequestRepairRouteImport.update({
  id: '/request-repair',
  path: '/request-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRepairRoute = TrackRepairRouteImport.update({
  id: '/track-repair',
  path: '/track-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyAndServiceRoute = WarrantyAndServiceRouteImport.update({
  id: '/warranty-and-service',
  path: '/warranty-and-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const EquipmentsSlugRoute = EquipmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquipmentsRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/admin/enquiries',
    path: '/admin/enquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImagesRoute =
  AuthenticatedAdminImagesRouteImport.update({
    id: '/admin/images',
    path: '/admin/images',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRepairRequestsRoute =
  AuthenticatedAdminRepairRequestsRouteImport.update({
    id: '/admin/repair-requests',
    path: '/admin/repair-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRepairsRoute =
  AuthenticatedAdminRepairsRouteImport.update({
    id: '/admin/repairs',
    path: '/admin/repairs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/admin/testimonials',
    path: '/admin/testimonials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrackingRoute =
  AuthenticatedAdminTrackingRouteImport.update({
    id: '/admin/tracking',
    path: '/admin/tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdRoute =
  AuthenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/equipments': typeof EquipmentsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/our-clients': typeof OurClientsRoute
  '/our-infrastructure': typeof OurInfrastructureRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRoute
  '/repair-process': typeof RepairProcessRoute
  '/request-repair': typeof RequestRepairRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-repair': typeof TrackRepairRoute
  '/warranty': typeof WarrantyRoute
  '/warranty-and-service': typeof WarrantyAndServiceRoute
  '/why-us': typeof WhyUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/equipments/$slug': typeof EquipmentsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/images': typeof AuthenticatedAdminImagesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/repair-requests': typeof AuthenticatedAdminRepairRequestsRoute
  '/admin/repairs': typeof AuthenticatedAdminRepairsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/equipments': typeof EquipmentsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/our-clients': typeof OurClientsRoute
  '/our-infrastructure': typeof OurInfrastructureRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRoute
  '/repair-process': typeof RepairProcessRoute
  '/request-repair': typeof RequestRepairRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-repair': typeof TrackRepairRoute
  '/warranty': typeof WarrantyRoute
  '/warranty-and-service': typeof WarrantyAndServiceRoute
  '/why-us': typeof WhyUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/equipments/$slug': typeof EquipmentsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/images': typeof AuthenticatedAdminImagesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/repair-requests': typeof AuthenticatedAdminRepairRequestsRoute
  '/admin/repairs': typeof AuthenticatedAdminRepairsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/equipments': typeof EquipmentsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/our-clients': typeof OurClientsRoute
  '/our-infrastructure': typeof OurInfrastructureRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRoute
  '/repair-process': typeof RepairProcessRoute
  '/request-repair': typeof RequestRepairRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-repair': typeof TrackRepairRoute
  '/warranty': typeof WarrantyRoute
  '/warranty-and-service': typeof WarrantyAndServiceRoute
  '/why-us': typeof WhyUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/equipments/$slug': typeof EquipmentsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/images': typeof AuthenticatedAdminImagesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/repair-requests': typeof AuthenticatedAdminRepairRequestsRoute
  '/_authenticated/admin/repairs': typeof AuthenticatedAdminRepairsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/brands'
    | '/careers'
    | '/contact'
    | '/equipments'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/our-clients'
    | '/our-infrastructure'
    | '/privacy'
    | '/privacy-policy'
    | '/quality'
    | '/repair-process'
    | '/request-repair'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/track-repair'
    | '/warranty'
    | '/warranty-and-service'
    | '/why-us'
    | '/admin/login'
    | '/blogs/$slug'
    | '/equipments/$slug'
    | '/services/$slug'
    | '/admin/enquiries'
    | '/admin/images'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/repair-requests'
    | '/admin/repairs'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tracking'
    | '/admin/'
    | '/admin/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/brands'
    | '/careers'
    | '/contact'
    | '/equipments'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/our-clients'
    | '/our-infrastructure'
    | '/privacy'
    | '/privacy-policy'
    | '/quality'
    | '/repair-process'
    | '/request-repair'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/track-repair'
    | '/warranty'
    | '/warranty-and-service'
    | '/why-us'
    | '/admin/login'
    | '/blogs/$slug'
    | '/equipments/$slug'
    | '/services/$slug'
    | '/admin/enquiries'
    | '/admin/images'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/repair-requests'
    | '/admin/repairs'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tracking'
    | '/admin'
    | '/admin/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/brands'
    | '/careers'
    | '/contact'
    | '/equipments'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/our-clients'
    | '/our-infrastructure'
    | '/privacy'
    | '/privacy-policy'
    | '/quality'
    | '/repair-process'
    | '/request-repair'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/track-repair'
    | '/warranty'
    | '/warranty-and-service'
    | '/why-us'
    | '/admin/login'
    | '/blogs/$slug'
    | '/equipments/$slug'
    | '/services/$slug'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/images'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/repair-requests'
    | '/_authenticated/admin/repairs'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/tracking'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EquipmentsRoute: typeof EquipmentsRouteWithChildren
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  IndustriesRoute: typeof IndustriesRoute
  OurClientsRoute: typeof OurClientsRoute
  OurInfrastructureRoute: typeof OurInfrastructureRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QualityRoute: typeof QualityRoute
  RepairProcessRoute: typeof RepairProcessRoute
  RequestRepairRoute: typeof RequestRepairRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrackRepairRoute: typeof TrackRepairRoute
  WarrantyRoute: typeof WarrantyRoute
  WarrantyAndServiceRoute: typeof WarrantyAndServiceRoute
  WhyUsRoute: typeof WhyUsRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipments': {
      id: '/equipments'
      path: '/equipments'
      fullPath: '/equipments'
      preLoaderRoute: typeof EquipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-infrastructure': {
      id: '/our-infrastructure'
      path: '/our-infrastructure'
      fullPath: '/our-infrastructure'
      preLoaderRoute: typeof OurInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-process': {
      id: '/repair-process'
      path: '/repair-process'
      fullPath: '/repair-process'
      preLoaderRoute: typeof RepairProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-repair': {
      id: '/request-repair'
      path: '/request-repair'
      fullPath: '/request-repair'
      preLoaderRoute: typeof RequestRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-repair': {
      id: '/track-repair'
      path: '/track-repair'
      fullPath: '/track-repair'
      preLoaderRoute: typeof TrackRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty-and-service': {
      id: '/warranty-and-service'
      path: '/warranty-and-service'
      fullPath: '/warranty-and-service'
      preLoaderRoute: typeof WarrantyAndServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/equipments/$slug': {
      id: '/equipments/$slug'
      path: '/$slug'
      fullPath: '/equipments/$slug'
      preLoaderRoute: typeof EquipmentsSlugRouteImport
      parentRoute: typeof EquipmentsRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/images': {
      id: '/_authenticated/admin/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AuthenticatedAdminImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/repair-requests': {
      id: '/_authenticated/admin/repair-requests'
      path: '/admin/repair-requests'
      fullPath: '/admin/repair-requests'
      preLoaderRoute: typeof AuthenticatedAdminRepairRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/repairs': {
      id: '/_authenticated/admin/repairs'
      path: '/admin/repairs'
      fullPath: '/admin/repairs'
      preLoaderRoute: typeof AuthenticatedAdminRepairsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tracking': {
      id: '/_authenticated/admin/tracking'
      path: '/admin/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders/$orderId': {
      id: '/_authenticated/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
  }
}

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersOrderIdRoute: typeof AuthenticatedAdminOrdersOrderIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersOrderIdRoute: AuthenticatedAdminOrdersOrderIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminImagesRoute: typeof AuthenticatedAdminImagesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminRepairRequestsRoute: typeof AuthenticatedAdminRepairRequestsRoute
  AuthenticatedAdminRepairsRoute: typeof AuthenticatedAdminRepairsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTrackingRoute: typeof AuthenticatedAdminTrackingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminImagesRoute: AuthenticatedAdminImagesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminRepairRequestsRoute: AuthenticatedAdminRepairRequestsRoute,
  AuthenticatedAdminRepairsRoute: AuthenticatedAdminRepairsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminTrackingRoute: AuthenticatedAdminTrackingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface EquipmentsRouteChildren {
  EquipmentsSlugRoute: typeof EquipmentsSlugRoute
}

const EquipmentsRouteChildren: EquipmentsRouteChildren = {
  EquipmentsSlugRoute: EquipmentsSlugRoute,
}

const EquipmentsRouteWithChildren = EquipmentsRoute._addFileChildren(
  EquipmentsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRouteWithChildren,
  BrandsRoute: BrandsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EquipmentsRoute: EquipmentsRouteWithChildren,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  IndustriesRoute: IndustriesRoute,
  OurClientsRoute: OurClientsRoute,
  OurInfrastructureRoute: OurInfrastructureRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QualityRoute: QualityRoute,
  RepairProcessRoute: RepairProcessRoute,
  RequestRepairRoute: RequestRepairRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrackRepairRoute: TrackRepairRoute,
  WarrantyRoute: WarrantyRoute,
  WarrantyAndServiceRoute: WarrantyAndServiceRoute,
  WhyUsRoute: WhyUsRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
